version: '3.8'
services:
  webapi:
    build:
      context: .   # Make sure this is pointing to the root of your project directory
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: fin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
volumes:
  postgres_data:
